[package]
name = "ft_ping_tester"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.158"
ratatui = "0.27.0"
serde = "1.0.209"
serde_derive = "1.0.209"
serde_json = "1.0.127"
signal-hook = "0.3.17"
toml = "0.8.19"
