[package]
name = "packets_interceptor"
version = "0.1.0"
edition = "2021"

[dependencies]
sudo = "0.6.0"
serde_json = "1.0.127"
pnet ="0.35.0"
pnet_packet ="0.35.0"
byteorder ="1.5.0"

[[bin]]
name = "packets_interceptor"
path = "src/main.rs"
